const hotelData = [
  {
    // id: 1,
    // HotelName: 'xyz',
    // Type: 'Doe',
    // City: 'url_to_avatar_image',
    // Photo: 'john.doe@example.com',
    // Title: 60000,
    // Describtion: 'Software Engineer',
    // rating: '2022-01-15',
    // rooms: 'Lorem ipsum dolor sit amet',
    hotelName: 'Luxury Hotel',
    hotelRating: 4.5,
    price: 250,
  },
  {
    // id: 2,
    // firstName: 'Jane',
    // lastName: 'Doe',
    // avatar: 'url_to_avatar_image',
    // email: 'jane.doe@example.com',
    // salary: 75000,
    // jobTitle: 'Product Manager',
    // startDate: '2022-02-01',
    // signatureCatchPhrase: 'Duis aute irure dolor in reprehenderit',
    hotelName: 'Seaside Resort',
    hotelRating: 4.2,
    price: 180,
  },
  {
    id: 3,
    firstName: 'Bob',
    lastName: 'Smith',
    avatar: 'url_to_avatar_image',
    email: 'bob.smith@example.com',
    salary: 50000,
    jobTitle: 'Graphic Designer',
    startDate: '2022-03-10',
    signatureCatchPhrase: 'Excepteur sint occaecat cupidatat non proident',
    hotelName: 'Mountain Lodge',
    hotelRating: 4.0,
    price: 120,
  },
  // Add more hotel entries as needed
];
export default  hotelData;